import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Men's striped fit T-shirt",
    image: "https://m.media-amazon.com/images/I/61rSf7lBx1L._UY500_.jpg",
    price: "1990",
    rating: 4.5,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Bigbanana Plus Size Fit Polo",
    image: "https://m.media-amazon.com/images/I/61UDal8a8oL._UY550_.jpg",
    price: "1399",
    rating: 4,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Wedani Women's Casual Top",
    image: "https://m.media-amazon.com/images/I/91vX8xWENOL._UY741_.jpg",
    price: "1999",
    rating: 2,
    type: "Women",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "AMERICAN Collar T-Shirt",
    image: "https://m.media-amazon.com/images/I/312kBG9174L.jpg",
    price: "1299",
    rating: 5,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Nusyl Girls Rainbow Printed Tshirt",
    image: "https://m.media-amazon.com/images/I/51cO10Ch7xL._UX679_.jpg",
    price: "999",
    rating: 4.4,
    type: "Kids",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "LEOTUDE Polo T-Shirt ",
    image: "https://m.media-amazon.com/images/I/71DNOWgs62L._UY550_.jpg",
    price: "314",
    rating: 3.8,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Wedani Regular Round Neck Top",
    image: "https://m.media-amazon.com/images/I/81dOdoQEB1L._UY741_.jpg",
    price: "999",
    rating: 4.1,
    type: "Women",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Veirdo Polo T Shirts for Men",
    image: "https://m.media-amazon.com/images/I/51i84HTi9kL._UX569_.jpg",
    price: "699",
    rating: 2.4,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Bigbanana Plus Size Fit Polo",
    image: "https://m.media-amazon.com/images/I/61UDal8a8oL._UY550_.jpg",
    price: "799",
    rating: 1,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "LEOTUDE Men's Half Sleeve",
    image: "https://m.media-amazon.com/images/I/71lrKzCZ+tL._UY550_.jpg",
    price: "1099",
    rating: 1.9,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "LEOTUDE Men's Half Sleeve T-Shirt",
    image: "https://m.media-amazon.com/images/I/71-TnQTYwML._UY550_.jpg",
    price: "899",
    rating: 2.8,
    type: "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Women's Synthetic Kurta",
    image: "https://m.media-amazon.com/images/I/812NWXrHNnL.jpg",
    price: "499",
    rating: 4.9,
    type: "Women",
    Material: "Cotton",
  },

  {
    _id: uuid(),
    title: "EYEBOGLER Round Neck T-Shirt",
    image: "https://m.media-amazon.com/images/I/41Z1YlOZuOL._UX569_.jpg",
    price: "259",
    rating: 5,
    type: "Kids",
    Material: "Cotton",
  },
];
