import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Men's striped fit T-shirt",
    image: "https://m.media-amazon.com/images/I/61rSf7lBx1L._UY500_.jpg",
    price: "1990",
    rating:4.5,
    type : "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Bigbanana Plus Size Fit Polo",
    image: "https://m.media-amazon.com/images/I/61UDal8a8oL._UY550_.jpg",
    price: "1399",
    rating:4,
    type : "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Women's Cotton Kurta",
    image: "https://m.media-amazon.com/images/I/81QN4uIauwL._AC_UL400_.jpg",
    price: "1999",
    rating:2,
    type : "Women",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "AMERICAN Collar T-Shirt Men",
    image: "https://m.media-amazon.com/images/I/312kBG9174L.jpg",
    price: "1299",
    rating:5,
    type : "Men",
    Material: "Cotton",
  },  {
    _id: uuid(),
    title: "Girls Cotton T-Shirt - Combo of 5 (KUC-TSHRT-0143)",
    image: "https://m.media-amazon.com/images/I/81eMNadh9EL._AC_UL400_.jpg",
    price: "999",
    rating:4.4,
    type : "Kid",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "LEOTUDE Polo T-Shirt (Color Grey)",
    image: "https://m.media-amazon.com/images/I/71DNOWgs62L._UY550_.jpg",
    price: "314",
    rating:3.8,
    type : "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Women's Synthetic Kurta",
    image: "https://m.media-amazon.com/images/I/81ye3FMqvoL._AC_UL400_.jpg",
    price: "999",
    rating:4.1,
    type : "Women",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Veirdo Polo T Shirts for Men",
    image: "https://m.media-amazon.com/images/I/51i84HTi9kL._UX569_.jpg",
    price: "699",
    rating:2.4,
    type : "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Bigbanana Plus Size Fit Polo",
    image: "https://m.media-amazon.com/images/I/61UDal8a8oL._UY550_.jpg",
    price: "799",
    rating:1,
    type : "Men",
    Material: "Cotton",
  }, 
  {
    _id: uuid(),
    title: "LEOTUDE Men's Half Sleeve",
    image: "https://m.media-amazon.com/images/I/71lrKzCZ+tL._UY550_.jpg",
    price: "1099",
    rating:1.9,
    type : "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "LEOTUDE Men's Half Sleeve Polo T-Shirt",
    image: "https://m.media-amazon.com/images/I/71-TnQTYwML._UY550_.jpg",
    price: "899",
    rating:2.8,
    type : "Men",
    Material: "Cotton",
  },
  {
    _id: uuid(),
    title: "Women's Synthetic Straight Kurta",
    image: "https://m.media-amazon.com/images/I/81laipB1Z3L._AC_UL400_.jpg",
    price: "499",
    rating:4.9,
    type : "Women",
    Material: "Cotton",
  },
  
  {
    _id: uuid(),
    title: "Boys T-Shirt",
    image: "https://m.media-amazon.com/images/I/A1HtatAa1-S._AC_UL400_.jpg",
    price: "259",
    rating:5,
    type : "Kid",
    Material: "Cotton",
  },
];
